# Generated by Django 5.2.1 on 2026-06-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category__name', 'name']},
        ),
        migrations.AddField(
            model_name='product',
            name='image_verified',
            field=models.BooleanField(default=False, help_text='Image matches name/category rules'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_eur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base price in EUR', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price_kes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='USD from live FX', max_digits=10),
        ),
    ]
