# Generated by Django 5.2.1 on 2026-06-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPortalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Staff portal',
                'verbose_name_plural': 'Staff portal',
                'permissions': [('access_staff_dashboard', 'Can access staff dashboard')],
            },
        ),
    ]
